FROM flink:1.15.0-scala_2.12-java11

WORKDIR /opt/flink/bin

COPY ./submit.sh /opt/flink/submit.sh
ADD submit.sh /
RUN chmod +x /submit.sh

COPY ./jars/*.jar /opt/FlinkJob.jar

ENTRYPOINT ["/submit.sh"]
